//Actions const

export const RETRIEVE_NOWPLAYING_LIST = "RETRIEVE_NOWPLAYING_LIST";
export const RETRIEVE_MOVIE_DETAIL = "RETRIEVE_MOVIE_DETAIL";
export const RETRIEVE_VIDEO = "RETRIEVE_VIDEO";
export const RETRIEVE_GENRE = "RETRIEVE_GENRE";
export const RETRIEVE_REVIEW = "RETRIEVE_REVIEW";
export const SEARCH_BY_GENRE = "SEARCH_BY_GENRE";
export const RETRIVE_UPCOMING = "RETRIVE_UPCOMING";
export const SAVE_MOVIE = "SAVE_MOVIE";
export const RETRIVE_SAVED_MOVIE = "RETRIVE_SAVED_MOVIE";
